#!/usr/bin/perl

while (<>) {
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

#                  12
#                  16
#               0   1   2
#            11             3
#    15  19  10             4   17 13
#            9              5
#               8   7   6
#                   18
#                   14

	$drive = 0;
	for ($i = 0; $i < 12; $i++) {
		$drive += $fields[$i];
	}

	$through = $fields[1] + $fields[7] + $fields[4] + $fields[10];
	$turn = $drive - $through;

	$walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];

	if ($drive != 0 && $walk != 0) {
		print "$drive $through $turn $walk $_";
	}
}
