#!/usr/bin/perl

while (<>) {
	s/^([0-9]*)-([0-9.]*)-([0-9.]*)-([0-9.]*)-([0-9.]*)/$1-$2,-$3-$4,-$5/;

	s/^(([0-9]*)-([0-9.]*),-([0-9.]*))/$3,-$4 $1/;

	($where, $file, $review, $session, $ip, $time) = split(/ /);
	print "$where $file $review $session $time";
}
