#!/usr/bin/perl

use strict;

my $pi = 4 * atan2(1, 1);
my $group = "";
my %val = ();

my $vertical = 2;

my $xmin = 1;
my $xmax = 200000;

my $height = 70;
my $wid = 500;

my $required = 500;

print "/Helvetica findfont 20 scalefont setfont\n";

while (<>) {
	chomp;

	if (/^group (.*)/) {
		$group = $1;
		print STDERR "group $group\n";
		next;
	}

	s/ .*//;

	if ($_ != 0) {
		s/^0*//;
		push @{$val{$group}}, log($_);
	}
}

my %groupmean = ();

for my $group (keys(%val)) {
	my @val = sort { $a <=> $b } @{$val{$group}};

	my $n = $#val + 1;
	next if $n < $required;

	my $sum = 0;
	for (my $i = 0; $i < $n; $i++) {
		$sum += $val[$i];
	}
	my $mean = $sum / $n;

	$groupmean{$group} = $mean;
	print STDERR "group $group: $mean\n";
}

$groupmean{'All data'} = -50;

my @groups = sort { $groupmean{$b} <=> $groupmean{$a} } keys(%groupmean);

my $base = 20;

my $gmean = 0;
my $gstddev = 0;
{
	my @val = ();

	for my $group (@groups) {
		push @val, @{$val{$group}};
	}

	my $n = $#val + 1;
	my $sum = 0;
	for (my $i = 0; $i < $n; $i++) {
		$sum += $val[$i];
	}
	$gmean = $sum / $n;

	my $diffsum = 0;
	for (my $i = 0; $i < $n; $i++) {
		$diffsum += ($val[$i] - $gmean) * ($val[$i] - $gmean);
	}
	my $variance = $diffsum / $n;
	$gstddev = sqrt($variance);
}

for my $group (@groups) {
	my @val = sort { $a <=> $b } @{$val{$group}};

	my $n = $#val + 1;
	my $sum = 0;
	for (my $i = 0; $i < $n; $i++) {
		$sum += $val[$i];
	}
	my $mean = $sum / $n;

	my $diffsum = 0;
	for (my $i = 0; $i < $n; $i++) {
		$diffsum += ($val[$i] - $mean) * ($val[$i] - $mean);
	}
	my $variance = $diffsum / $n;
	my $stddev = sqrt($variance);

	next if $stddev == 0;

	my $increment = $gstddev / 4;
	my $maxy = 0;

	my @x = ();
	my @y = ();

	for (my $i = $gmean - 3 * $gstddev; $i < $gmean + 3 * $gstddev; $i += $increment) {
		my $count = 0;
		for (my $j = 0; $j < $n; $j++) {
			if ($val[$j] >= $i && $val[$j] < $i + $increment) {
				$count++;
			}
		}

		push @x, $i;
		push @y, $count;

		if ($count > $maxy) {
			$maxy = $count;
		}
	}

	push @x, $gmean + 3 * $gstddev;

	my $peak = $n * $increment / ($stddev * sqrt(2 * $pi)) * exp(- ($mean - $mean) * ($mean - $mean) / (2 * $stddev * $stddev));

	for (my $i = 0; $i < $#x; $i++) {
		printf("%.3f %.3f %s ", 50 + $wid * ($x[$i] - log($xmin)) / (log($xmax) - log($xmin)), $height * $y[$i] / $peak + $base,
			$i == 0 ? "moveto" : "lineto");
		printf("%.3f %.3f %s ", 50 + $wid * ($x[$i + 1] - log($xmin)) / (log($xmax) - log($xmin)), $height * $y[$i] / $peak + $base,
			"lineto");
	}

	print "stroke\n";

	if (1) {
		for (my $i = 0; $i <= $#x; $i += .1) {
			my $frac = $i - int($i);

			my $v = $x[$i + 1] * $frac + $x[$i] * (1 - $frac);
			my $y = $n * $increment / ($stddev * sqrt(2 * $pi)) * exp(- ($v - $mean) * ($v - $mean) / (2 * $stddev * $stddev));

			# print STDERR "$y\n";

			printf("%.3f %.3f %s ", 50 + $wid * ($v - log($xmin)) / (log($xmax) - log($xmin)), $height * $y / $peak + $base,
				$i == 0 ? "moveto" : "lineto");
		}

		print "stroke\n";
	}

	print "/Helvetica findfont 20 scalefont setfont\n";
	printf("%.3f %.3f moveto ", 50 + $wid * ($gmean + 3.5 * $gstddev - log($xmin)) / (log($xmax) - log($xmin)), $base - 5);
	printf("(%s) show stroke\n", $group);

	print "/Helvetica findfont 15 scalefont setfont\n";
	printf("%.3f %.3f moveto ", 50 + $wid * ($mean - log($xmin)) / (log($xmax) - log($xmin)), $base - 10);
	printf("(%d) dup stringwidth pop 2 div neg 0 rmoveto show stroke\n", exp($mean));

	print "/Helvetica findfont 12 scalefont setfont\n";
	printf("%.3f %.3f moveto ", 50 + $wid * ($mean + $stddev - log($xmin)) / (log($xmax) - log($xmin)), $base - 10);
	printf("(%d) dup stringwidth pop 2 div neg 0 rmoveto show stroke\n", exp($mean + $stddev));

	printf("%.3f %.3f moveto ", 50 + $wid * ($mean - $stddev - log($xmin)) / (log($xmax) - log($xmin)), $base - 10);
	printf("(%d) dup stringwidth pop 2 div neg 0 rmoveto show stroke\n", exp($mean - $stddev));

	printf("%.3f %.3f moveto ", 50 + $wid * ($mean + 1.5 * $stddev - log($xmin)) / (log($xmax) - log($xmin)), $base - 10);
	printf("(%d) dup stringwidth pop 2 div neg 0 rmoveto show stroke\n", exp($mean + 1.5 * $stddev));

	printf("%.3f %.3f moveto ", 50 + $wid * ($mean - 1.5 * $stddev - log($xmin)) / (log($xmax) - log($xmin)), $base - 10);
	printf("(%d) dup stringwidth pop 2 div neg 0 rmoveto show stroke\n", exp($mean - 1.5 * $stddev));

	$base += $height * $maxy / $peak + 20;
}

if (0) {
	printf("%.3f %.3f moveto %.3f %.3f lineto stroke\n",
		50 + $wid * ($gmean - log($xmin)) / (log($xmax) - log($xmin)), 0,
		50 + $wid * ($gmean - log($xmin)) / (log($xmax) - log($xmin)), $base);

	printf("%.3f %.3f moveto %.3f %.3f lineto stroke\n",
		50 + $wid * ($gmean + $gstddev - log($xmin)) / (log($xmax) - log($xmin)), 0,
		50 + $wid * ($gmean + $gstddev - log($xmin)) / (log($xmax) - log($xmin)), $base);

	printf("%.3f %.3f moveto %.3f %.3f lineto stroke\n",
		50 + $wid * ($gmean + 1.5 * $gstddev - log($xmin)) / (log($xmax) - log($xmin)), 0,
		50 + $wid * ($gmean + 1.5 * $gstddev - log($xmin)) / (log($xmax) - log($xmin)), $base);

	printf("%.3f %.3f moveto %.3f %.3f lineto stroke\n",
		50 + $wid * ($gmean - $gstddev - log($xmin)) / (log($xmax) - log($xmin)), 0,
		50 + $wid * ($gmean - $gstddev - log($xmin)) / (log($xmax) - log($xmin)), $base);

	printf("%.3f %.3f moveto %.3f %.3f lineto stroke\n",
		50 + $wid * ($gmean - 1.5 * $gstddev - log($xmin)) / (log($xmax) - log($xmin)), 0,
		50 + $wid * ($gmean - 1.5 * $gstddev - log($xmin)) / (log($xmax) - log($xmin)), $base);
}

print STDERR "ps2pdf -dDEVICEHEIGHTPOINTS=$base\n";
