#!/usr/bin/perl

if ($ARGV[0] eq "-p") {
	$plot = 1;
	shift (@ARGV);
}

$baseline = 16.75;  # 16:45-17:00
$morning = 10.5;    # 10:30-10:45

while (<>) {
	($id, $name, $id2, $date, $time, @fields) = split(/,/);

	if ($time =~ /^(..):(..) *- *(..):(..)$/) {
		$time = $1 + $2 / 60;
		$time2 = $3 + $4 / 60;
	} else {
		if (!$seen{$time}) {
			print STDERR "don't know what to do with time $time\n";
		}
		$seen{$time} = 1;
		next;
	}

	$key = "$id,$name,$id2,$date";

	if ($key ne $okey) {
		if ($walk{$baseline} != 0 && $walk{$morning} != 0) {
			$walkbasesum += $walk{$baseline};
			$walkbasecount++;

			for $n (sort { $a <=> $b } keys(%walk)) {
				if ($walk{$n} != 0) {
					$walksum{$n} += log($walk{$n} / $walk{$baseline});
					$walkcount{$n} += 1;
				}
			}
		}

		if ($drive{$baseline} != 0 && $drive{$morning} != 0) {
			$drivebasesum += $drive{$baseline};
			$drivebasecount++;

			for $n (sort { $a <=> $b } keys(%drive)) {
				if ($drive{$n} != 0) {
					$drivesum{$n} += log($drive{$n} / $drive{$baseline});
					$drivecount{$n} += 1;
				}
			}
		}

		if ($bike{$baseline} != 0 && $bike{$morning} != 0) {
			$bikebasesum += $bike{$baseline};
			$bikebasecount++;

			for $n (sort { $a <=> $b } keys(%bike)) {
				if ($bike{$n} != 0) {
					$bikesum{$n} += log($bike{$n} / $bike{$baseline});
					$bikecount{$n} += 1;
				}
			}
		}

		%walk = ();
		%drive = ();
		%bike = ();
		$okey = $key;
	}

	if ($time2 == $time + .25) {
		$walk = $fields[12] + $fields[13] + $fields[14] + $fields[15];
		$walk{$time} = $walk;

		$bike = $fields[16] + $fields[17] + $fields[18] + $fields[19];
		$bike{$time} = $bike;

		$drive{$time} = 0;
		for ($i = 0; $i < 12; $i++) {
			$drive{$time} += $fields[$i];
		}
	}
}

if (!$plot) {
	print "\@walk_scale = (\n";
	for ($i = 0; $i < 24; $i++) {
		print "\t";
		for ($j = $i; $j < $i + 1; $j += .25) {
			$walk = $walksum{$j} / $walkcount{$j};
			printf("%.6f, ", exp($walk));
		}
		print "\n";
	}
	print ");\n\n";

	print "\@drive_scale = (\n";
	for ($i = 0; $i < 24; $i++) {
		print "\t";
		for ($j = $i; $j < $i + 1; $j += .25) {
			$drive = $drivesum{$j} / $drivecount{$j};
			printf("%.6f, ", exp($drive));
		}
		print "\n";
	}
	print ");\n\n";

	print "\@bike_scale = (\n";
	for ($i = 0; $i < 24; $i++) {
		print "\t";
		for ($j = $i; $j < $i + 1; $j += .25) {
			$walk = $walksum{$j} / $walkcount{$j};
			$drive = $drivesum{$j} / $drivecount{$j};

			if ($bikecount{$j} > 10) {
				$bike = $bikesum{$j} / $bikecount{$j};
				printf("%.6f, ", exp($bike));
			} else {
				printf("%.5f,  ", exp(($walk + $drive) / 2));
			}
		}
		print "\n";
	}
	print ");\n\n";
} else {
	for $n (sort { $a <=> $b } keys(%walksum)) {
		$walk = $walksum{$n} / $walkcount{$n};
		$drive = $drivesum{$n} / $drivecount{$n};

		if ($bikecount{$n} > 10) {
			$bike = $bikesum{$n} / $bikecount{$n};
		} else {
			$bike = ($walk + $drive) / 2;
		}

		if ($bikecount{$n} > 10) {
			printf("%s %.6f %.6f %.6f\n", $n, exp($walk), exp($drive), exp($bike));
		} else {
			printf("%s %.6f %.6f %.6f guess\n", $n, exp($walk), exp($drive), exp($bike));
		}
	}
}
