#!/usr/bin/perl

while (<>) {
	chomp;
	@fields = split(/,/);

	# print "$fields[4]\n";

	#                17
	#            5   6   7
        #        16             8
        #   20   15             9      18
        #        14             10
        #           13   12  11
	#                19

	$turn = $fields[5] + $fields[7] +
		$fields[8] + $fields[10] +
		$fields[11] + $fields[13] +
		$fields[14] + $fields[16];

	$walk = $fields[17] + $fields[18] + $fields[19] + $fields[20];

	print "$turn $walk\n";
}
